name: CI with Gradle (Build, Test & SonarQube)

on:
  push:
    branches:
      - master
      - Feature/add-pipeline
  pull_request:
    branches:
      - master
      - Feature/add-pipeline

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and Run Tests
        run: ./gradlew build test --info --stacktrace

      - name: Afficher les tests exécutés
        run: |
          echo "Tests exécutés :"
          cat build/reports/tests/test/index.html || echo "Fichier de rapport non trouvé"

  launch-sonarqube:
    name: Launch SonarQube
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Rebuild the Project
        run: ./gradlew build -x test --stacktrace

      - name: List Build Directory After Rebuild
        run: ls -R sonar-application/build/ || echo "No build directory found!"

      - name: Extract SonarQube Distribution
        run: |
          ZIP_FILE=$(find sonar-application/build/distributions/ -name "*.zip" | head -n 1)
          if [ -z "$ZIP_FILE" ]; then
            echo "No ZIP file found! Exiting..."
            exit 1
          fi
          echo "Extracting $ZIP_FILE..."
          unzip "$ZIP_FILE" -d sonar-application/build/distributions/

      - name: Grant Execution Permission
        run: chmod +x sonar-application/build/distributions/*/bin/linux-x86-64/sonar.sh

      - name: Start SonarQube
        run: |
          sonar-application/build/distributions/*/bin/linux-x86-64/sonar.sh start

      - name: Display SonarQube Logs
        run: cat sonar-application/build/distributions/*/logs/sonar.log || echo "No logs found!"

      - name: Run SonarQube Analysis
        run: ./gradlew sonarqube --stacktrace
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.d305883d57373544439a5bdd5f30b398bbf68ed7 }}

      - name: Check Cyclomatic Complexity
        run: |
          COMPLEXITY=$(curl -s "https://sonarcloud.io/api/measures/component?component=d305883d57373544439a5bdd5f30b398bbf68ed7&metricKeys=complexity" -H "Authorization: Bearer ${{ secrets.d305883d57373544439a5bdd5f30b398bbf68ed7 }}" | jq -r '.component.measures[0].value')
          echo "Complexité détectée : $COMPLEXITY"
          if [ "$COMPLEXITY" -gt 500 ]; then
            echo "ERREUR: La complexité dépasse la limite autorisée (500) !"
            exit 1
          fi