name: CI with Gradle (Start SonarQube Only)

on:
  workflow_dispatch: # Permet d'exécuter manuellement depuis GitHub Actions

jobs:
  launch-sonarqube:
    name: Start SonarQube
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl --fail http://localhost:9000/api/system/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --memory=2g  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for SonarQube to be ready
        run: |
          echo "Waiting for SonarQube to be up..."
          until curl -s http://localhost:9000/api/system/status | grep -q '"status":"UP"'; do
            echo "Still waiting..."
            sleep 5
          done

      - name: Check SonarQube health
        run: curl -s http://localhost:9000/api/system/health | jq .
