name: Complexity Analysis with SonarCloud

on:
  push:
    branches:
      - main
      - Feature/add-pipeline
  pull_request:
    branches:
      - main
      - Feature/add-pipeline

jobs:
  complexity-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Run ESLint for complexity analysis
        run: npx eslint . || true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.d305883d57373544439a5bdd5f30b398bbf68ed7 }}

      - name: Vérifier la complexité SonarCloud
        run: |
          SONAR_COMPLEXITY=$(curl -s "https://sonarcloud.io/api/measures/component?component=d305883d57373544439a5bdd5f30b398bbf68ed7&metricKeys=complexity" -H "Authorization: Bearer ${{ secrets.d305883d57373544439a5bdd5f30b398bbf68ed7 }}" | jq '.component.measures[0].value | 500')
          echo "Complexité Cyclomatique Totale: $SONAR_COMPLEXITY"
          if [ "$SONAR_COMPLEXITY" -gt 500 ]; then
            echo "🚨 ERREUR: La complexité du projet dépasse la limite autorisée !"
            exit 1
          fi
